# Generated by Django 3.2.4 on 2026-09-08 12:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_alter_ordermodel_paid_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid 10-digit Indian mobile number.', regex='^[6-9]\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='pin_code',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Enter a valid 6-digit PIN code.', regex='^\\d{6}$')]),
        ),
    ]
