# Generated by Django 3.2.4 on 2026-09-09 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_auto_20260908_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='landmark',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
